services:
  cuarto-cerrado:
    build: .
    container_name: cuarto-cerrado
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - ./data:/app/data
